on:
  workflow_call:
    secrets:
      apiToken:
        description: 'Terraform Cloud API Token'
        required: true
      gitHubToken:
        description: 'GitHub Token'
        required: true
    inputs:
      resourceGroup:
        description: 'Name of the reosurce group'
        required: true
        type: "string"
      environment:
        description: 'Name of the Environment'
        required: true
        type: "string"
      region:
        description: 'Name of the region where resources will be created'
        required: true
        type: "string"
      team:
        description: 'Name of the team responsible for the resources'
        required: true
        type: "string"

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v5
      with:
          # super-linter needs the full git history to get the list of files that changed across commits
          fetch-depth: 0
          persist-credentials: false

    - name: Super-linter
      uses: super-linter/super-linter@v8.3.1
      env:
        # To report GitHub Actions status checks
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.apiToken }}

    ## Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
    
    # Valdiate all Terraform configuration
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      id: plan
      run: terraform plan -var=resource_group_name=${{ inputs.resourceGroup }} -var=environment=${{ inputs.environment }} -var=team=$${{ inputs.team }} -var=location=${{ inputs.region}}

    # Update Terraform pull request
    - name: Update Pull Request
      uses: actions/github-script@v6.0.0
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.gitHubToken }}
        script: |
          const output = `#### Terraform Format and Style üñå\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ‚öôÔ∏è\`${{ steps.init.outcome }}\`
          #### Terraform Plan üìñ\`${{ steps.plan.outcome }}\`
          #### Terraform Validation ü§ñ\`${{ steps.validate.outcome }}\`
          <details><summary>Show Plan</summary>
          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`
          </details>
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
          
      # On push to main, build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -var=resource_group_name=${{ inputs.resourceGroup }} -var=environment=${{ inputs.environment }} -var=location=${{ inputs.region}}